import Head from 'next/head'
import { useEffect } from 'react'
import { supabase } from '../utils/supabaseClient'

export default function Home() {
  useEffect(() => {
    const getAuth = async () => {
      const { user, session, error } = await supabase.auth.signIn({
        email: 'clark.wood@protonmail.com',
        password: 'c4gnv-pass'
      })
      console.log("USER: " + JSON.stringify(user))
      console.log("SESSION: " + JSON.stringify(session))
      console.log("ERROR: " + JSON.stringify(error))

      const data = await supabase
      .from('programs')
      .select('*')
      console.log("PROGRAMS: " + JSON.stringify(data.data))
    }
    getAuth()
  }, [])

  return (
    <div>
      <Head>
        <title>myGNV Resource Finder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Resource Finder</h1>
      </main>
    </div>
  )
}
