import Head from 'next/head'
import { useEffect } from 'react'
import { supabase } from '../utils/supabaseClient'
import { definitions } from '../models/supabase'

export default function Home() {
  useEffect(() => {
    const getAuth = async () => {

     // departments
     // services
     // tags = categories
     // programs

      // 1a) Get a list of amenities
      const { data, error } = await supabase
        .rpc('amenity_list')
      // 1b) Loop through amenities, get their locations
      if (!error && data) {
        data.forEach(function (amenity) {
          console.log(amenity.name)
          amenity.locations.forEach(function (location: definitions['locations']) {
            console.log("\t" + location.name)
          })
        })
      }

      // 2a)

    }
    getAuth()
  }, [])

  return (
    <div>
      <Head>
        <title>myGNV Resource Finder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Resource Finder</h1>
      </main>
    </div>
  )
}
