import Head from 'next/head'
import { useEffect, useState } from 'react'
import { supabase } from '../utils/supabaseClient'

export default function Home() {
  console.log("HERE");
  const [loading, setLoading] = useState(true)
  const [user, setUser] = useState(null)
  const [session, setSession] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    getAuth()
  }, [])

    const getAuth = async () => {
      setLoading(true)
      let { user, session, error } = await supabase.auth.signIn({
        email: 'clark.wood@protonmail.com',
        password: 'c4gnv-pass'
      })
      console.log("USER: " + JSON.stringify(user))
      console.log("SESSION: " + JSON.stringify(session))
      console.log("ERROR: " + JSON.stringify(error))

      let { data, error2, status } = await supabase
      .from('programs')
      .select('*')
      console.log("PROGRAMS: " + JSON.stringify(data))

      setLoading(false)
    }

  return (
    <div>
      <Head>
        <title>myGNV Resource Finder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>Resource Finder</h1>
      </main>
    </div>
  )
}
