name: Development Workflow

on: [push, pull_request_target]

jobs:
  shouldRun:
    runs-on: ubuntu-latest
    outputs:
      shouldRun: ${{ steps.check.outputs.shouldRun }}
    env:
      VALID_EVENT: ${{ (github.event_name == 'pull_request_target' && github.event.pull_request.user.login == 'dependabot[bot]') || github.event_name == 'push' }}
    steps:
      - id: check
        run: |
          if [[ "$VALID_EVENT" != true ]];
          then echo "::set-output name=shouldRun::false";
          else echo "::set-output name=shouldRun::true"; fi

  lint:
    needs: shouldRun
    if: needs.shouldRun.outputs.shouldRun == 'true' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2.3.4
      - if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /tmp/.yarn_cache
          key: v5-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Yarn
        run: yarn --pure-lockfile --cache-folder /tmp/.yarn_cache
      - name: Cache dependency tree
        uses: actions/cache@v2
        with:
          path: ./tmp/.changescache
          key: v5-dep-tree
      - name: Lint
        run: yarn lint

  test:
    needs: shouldRun
    if: needs.shouldRun.outputs.shouldRun == 'true'
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name != 'pull_request_target'
        uses: actions/checkout@v2.3.4
      - if: github.event_name == 'pull_request_target'
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /tmp/.yarn_cache
          key: v5-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Yarn
        run: yarn --pure-lockfile --cache-folder /tmp/.yarn_cache
      - name: Cache dependency tree
        uses: actions/cache@v2
        with:
          path: ./tmp/.changescache
          key: v5-dep-tree
      - name: Jest
        run: yarn test

  deploy:
    needs:
      - shouldRun
      - lint
      - test
    if: needs.shouldRun.outputs.shouldRun == 'true' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Development Code
        uses: actions/checkout@v2

      - name: Deploy client to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
